export const devices = [
  { name: "DG-1", ip: "XXX.XXX.X.1" },
  { name: "DG-2", ip: "XXX.XXX.X.2" },
  { name: "TRF-1", ip: "XXX.XXX.X.3" },
  { name: "TRF-2", ip: "XXX.XXX.X.4" },
  { name: "MAIN INCOMER", ip: "XXX.XXX.X.5" },
  { name: "UTILITY PANEL", ip: "XXX.XXX.X.6" },
  { name: "CHILLER-1", ip: "XXX.XXX.X.7" },
  { name: "CHILLER-2", ip: "XXX.XXX.X.8" },
  { name: "COMPRESSOR", ip: "XXX.XXX.X.9" },
  { name: "LIGHTING", ip: "XXX.XXX.X.10" },
  { name: "FLOOR-1", ip: "XXX.XXX.X.11" },
  { name: "FLOOR-2", ip: "XXX.XXX.X.12"},
  { name: "HVAC", ip: "XXX.XXX.X.13" },
  { name: "FILLER-1", ip: "XXX.XXX.X.14" },
  { name: "FILLER-2", ip: "XXX.XXX.X.15" },
  { name: "FILLER-3", ip: "XXX.XXX.X.16" },
  { name: "PUMP-1", ip: "XXX.XXX.X.17" },
  { name: "PUMP-2", ip: "XXX.XXX.X.18" },
  { name: "PUMP-3", ip: "XXX.XXX.X.19" },
  { name: "DEPALLETIZER-1", ip: "XXX.XXX.X.20" },
  { name: "DEPALLETIZER-2", ip: "XXX.XXX.X.21" },
  { name: "DEPALLETIZER-3", ip: "XXX.XXX.X.22" },
  { name: "PALLETIZER-1", ip: "XXX.XXX.X.23" },
  { name: "PALLETIZER-2", ip: "XXX.XXX.X.24" },
  { name: "PALLETIZER-3", ip: "XXX.XXX.X.25" },
  { name: "HUB", ip: "XXX.XXX.X.26" }
];
